artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model_prep:
  root_dir: artifacts/base_model_prep
  base_model_path: artifacts/base_model_prep/base_model.h5
  updated_base_model_path: artifacts/base_model_prep/updated_base_model.h5


callbacks_prep:
  root_dir: artifacts/callbacks_prep
  tensorboard_root_log_dir: artifacts/callbacks_prep/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks_prep/checkpoint_dir/model.h5

model_training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5



